import type { Metadata } from "next";

import Header from "../util/Header";
import Footer from "../util/Footer";

export const metadata: Metadata = {
  title: "Transpot marketplace",
  description: "Generated by create next app",
};

export default function WebsiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
